
service: elongate
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

plugins:
  - serverless-domain-manager
  
custom:                                             # settings for the plugins: 
  customDomain:                                     # | custom domain:
    domainName: "elongate-api.loganevans.me"      # --> 
    stage: ${opt:stage,'dev'}                       # --> adds /prod/ or /dev/
    basePath: ${opt:stage,'dev'}                    # --> everything 
    region: us-east-1                               # --> in us-east-1
    certificateName: "*.loganevans.me"          # --> TLS certificate in ACM
    endpointType: "regional"                        # --> regional endpoint
    securityPolicy: tls_1_2                         # --> TLS 1.2
    createRoute53Record: true                       # --> creates / replaces Route53 record
    apiType: rest                                   # --> REST API
    autoDomain: true                                # --> ?

functions:
  checkTweets:
    handler: app.check_tweets
    events:
      - schedule: rate(1 minute)
  analyzeTweet:
    handler: app.analyze_tweet
    events:
      - http:
          path: analyze
          method: any
          cors: true
  notifyResult:
     handler: app.notify_result