
service: elongate
frameworkVersion: '2'

provider:
  name: aws
  region: eu-west-3
  runtime: python3.8
  lambdaHashingVersion: 20201221
  iamRoleStatements:                      # make sure to use the bare minimums - note and reduce
    - Effect: "Allow"                     # give lambda permissions for...
      Action:                             # 
        - "ssm:GetParameter"              # for SSM getting keys and such
        - "comprehend:DetectSentiment"              # for SSM getting keys and such
      Resource:
        - "arn:aws:ssm:us-east-1:311306608161:parameter/elongate*"     
        - "*"     

#plugins:
#  - serverless-domain-manager
  
custom:                                             # settings for the plugins: 
  pythonRequirements:
    usePoetry: true
  #customDomain:                                     # | custom domain:
  #  domainName: "elongate-.loganevans.me"      # --> 
  #  stage: ${opt:stage,'dev'}                       # --> adds /prod/ or /dev/
  #  basePath: ${opt:stage,'dev'}                    # --> everything 
  #  region: eu-west-3                               # --> in us-east-1
  #  certificateName: "*.loganevans.me"          # --> TLS certificate in ACM
  #  endpointType: "regional"                        # --> regional endpoint
  #  securityPolicy: tls_1_2                         # --> TLS 1.2
  #  createRoute53Record: true                       # --> creates / replaces Route53 record
  #  apiType: rest                                   # --> REST API
  #  autoDomain: true                                # --> ?

functions:
  checkRecentElonTweets:
    handler: app.check_recent_elon_tweets
    events:
      - http:
          path: recent
          method: any
          cors: true
  analyzeTweet:
    handler: app.analyze_tweet
    events:
      - http:
          path: analyze
          method: any
          cors: true
  notifyResult:
     handler: app.notify_result
